# Generated by Django 6.0.5 on 2026-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=models.ImageField(blank=True, default='default_work.jpg', null=True, upload_to='core/work/'),
        ),
    ]
