# Generated by Django 6.0.5 on 2026-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=models.ImageField(blank=True, default='media/default_work.jpg', null=True, upload_to='media/core/work/'),
        ),
    ]
