# Generated by Django 6.0.5 on 2026-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_work_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=models.ImageField(blank=True, default='default_work.jpg', null=True, upload_to='media/core/work/'),
        ),
    ]
