# Generated by Django 6.0.5 on 2026-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_work_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=models.ImageField(blank=True, default='default_work.png', null=True, upload_to='core/work/'),
        ),
    ]
