# Generated by Django 6.0.5 on 2026-06-04 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_work_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
