# Generated by Django 6.0.6 on 2026-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_work_created_at_work_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(max_length=100, null=True)),
                ('os_name', models.CharField(blank=True, max_length=255)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=500)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fingerprint', 'path'), name='unique_visitor_page')],
            },
        ),
    ]
