# Generated by Django 6.0.6 on 2026-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
