# Generated by Django 6.0.6 on 2026-06-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_visitor_browser_version_alter_visitor_last_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name_plural': 'Visitor'},
        ),
        migrations.RemoveConstraint(
            model_name='visitor',
            name='unique_visitor_page',
        ),
    ]
