# Generated by Django 6.0.6 on 2026-06-16 06:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_work.png', max_length=255, null=True, verbose_name='aninda_portfolio_picture'),
        ),
    ]
