# Generated by Django 6.0.6 on 2026-06-17 13:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_work_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='core/work/default_work.png', max_length=255, null=True),
        ),
    ]
